version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  order_processor:
    build: 
      context: ../.
      dockerfile: ./build/package/order_processor/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
