version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
  order_processor:
    build: 
      context: ../cmd/order_processor
      dockerfile: ../../build/package/order_processor/Dockerfile
    ports:
      - "5000:5000"
